background {
    path = screenshot
    blur_passes = 12
    blur_size = 15
}

input-field {
    size = 300, 50
    position = 0, -80
    halign = center
    valign = center
}

label {
    text = $TIME
    font_size = 50
    position = 0, 80
    halign = center
    valign = center
}
