set -s escape-time 0

# Reload config 
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Set base index to 1 
set -g base-index 1

# Vim-style pane switching
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Resize panes
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2

# Use vi keys in copy mode
setw -g mode-keys vi

# Copy to system clipboard using xclip
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# MOUSE SUPPORT
#set -g mouse on


